const animals = [
    {
        id: 1,
        name: "nannakookaburra",
        image_src: "assets/nannakookaburra.png",
        bio_name: "Kookaburra",
        bio_wadawurrung_name: "Kuwarrk",
        bio_scientific_name: "Dacelo novaeguineae",
        bio_size_range: "40 - 45 cm",
        bio_weight: "0.31 - 0.38 kg",
        animal_sound_src: "assets/audio/kookaburra.mp3",
        animal_audio_story_src: "assets/audio/storynannakookaburra.mp3",
        animal_story_para1: "Nanna Kookaburra was perched on a signpost waiting patiently for you to take her home. Nanna Kookaburra never got lost. She always knew where she was. But sometimes she needed a little help remembering where she was going.",
        animal_story_para2: "“Hello possum!” said Nanna Kookaburra, who called everyone possum, even if they weren’t. “I’m looking for my home, but I can’t quite remember where it is! Be a dear and help me find it will you.”",
        animal_story_para3: "So, she perched on your shoulder and off you both went to ask all the animals along the trail just where Nanna Kookaburra might be going.",
        animal_facts: "Laughing Kookaburras pair for life. The dad and mum take turns keeping eggs warm and sometimes the older brothers and sisters of a kookaburra chick will help with babysitting!"
    },
    {
        id: 2,
        name: "motherkoalawithjoey",
        image_src: "assets/motherkoalawithjoey.png",
        bio_name: "Koala",
        bio_wadawurrung_name: "Ngaambulmum",
        bio_scientific_name: "Phascolarctos cinereus",
        bio_size_range: "60 - 85 cm",
        bio_weight: "8 - 12kg",
        animal_sound_src: "assets/audio/koala.mp3",
        animal_audio_story_src: "assets/audio/storymotherkoalawithjoey.mp3",
        animal_story_para1: "Nanna Kookaburra found Mother Koala and Joey Koala resting in some shade. “Where are you heading, Nanna Kookaburra?” asked Mother Koala. “Hello possums!” said Nanna Kookaburra. “I’m heading home love, but I can’t remember where it is.”",
        animal_story_para2: "“Hehe! We’re not possums! We’re Koalas,” giggled Joey Koala who lived inside her mother’s pouch. “It’s somewhere that feels like a hug, it is, it’s somewhere that feels like a hug.”",
        animal_story_para3: "Joey Koala gave Nanna Kookaburra a warm hug and Nanna Kookaburra continued along the trail.",
        animal_facts: "Koalas can sleep for up to 20 hours a day! This is because they have a low energy diet, and use most of their energy eating the leaves they need to get energy!"
    },
    {
        id: 3,
        name: "auntiemagpie",
        image_src: "assets/auntiemagpie.png",
        bio_name: "Magpie",
        bio_wadawurrung_name: "Parrwang",
        bio_scientific_name: "Cracticus tibicen",
        bio_size_range: "36 - 44cm",
        bio_weight: "0.22 - 0.36kg",
        animal_sound_src: "assets/audio/storyauntiemagpie.mp3",
        animal_audio_story_src: "assets/audio/magpie.mp3",
        animal_story_para1: "Nanna Kookaburra found Auntie Magpie hiding in some leaves. “Where are you heading, Nanna Kookaburra?” asked Auntie Magpie.",
        animal_story_para2: "“Hello possum!” said Nanna Kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” warbled Auntie Magpie who lived in a tree, “It’s somewhere that’s always safe, it is, it’s somewhere that’s always safe.”",
        animal_story_para3: "Auntie Magpie gave Nanna Kookaburra a long green leaf and Nanna Kookaburra continued along the trail.",
        animal_facts: "Females have grey and speckled feathers on the back of their necks, while males only have white on the back of their necks!"
    },
    {
        id: 4,
        name: "unclemagpie",
        image_src: "assets/unclemagpie.png",
        bio_name: "Magpie",
        bio_wadawurrung_name: "Parrwang",
        bio_scientific_name: "Cracticus tibicen",
        bio_size_range: "36 - 44cm",
        bio_weight: "0.22 - 0.36kg",
        animal_sound_src: "assets/audio/storyunclemagpie.mp3",
        animal_audio_story_src: "assets/audio/magpie.mp3",
        animal_story_para1: "Nanna Kookaburra found Uncle Magpie high in a tree. “Where are you heading, Nanna Kookaburra?” asked Uncle Magpie. ",
        animal_story_para2: "“Hello possum!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” sung Uncle Magpie as he spotted a worm. “It’s somewhere with the best grub, it is, it’s somewhere with the best grub.”",
        animal_story_para3: "Uncle Magpie gave Nanna Kookaburra a juicy worm and Nanna Kookaburra continued along the trail.",
        animal_facts: "Much like cockatoos and parrots, magpies can mimic over 30 other birds! They can also mimic dogs barking, telephones ringing, police sirens and people!"
    },
    {
        id: 5,
        name: "granddaughterkookaburra",
        image_src: "assets/granddaughterkookaburra.png",
        bio_name: "Kookaburra",
        bio_wadawurrung_name: "Kuwarrk",
        bio_scientific_name: "Dacelo novaeguineae",
        bio_size_range: "40 - 45 cm",
        bio_weight: "0.31 - 0.38 kg",
        animal_sound_src: "assets/audio/kookaburra.mp3",
        animal_audio_story_src: "assets/audio/storygranddaughterkookaburra.mp3",
        animal_story_para1: "Nanna Kookaburra found her Granddaughter Kookaburra perched on a tree, smiling down at her. “Where are you heading, Nanna Kookaburra?” asked Granddaughter Kookaburra.",
        animal_story_para2: "“Hello, my dear!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” laughed her Granddaughter. “It’s somewhere you never feel lost, it is, yeah it’s somewhere you never feel lost.”",
        animal_story_para3: "“I never feel lost around you, my dear,” squawked Nanna Kookaburra. “Okay! I’ll come with you then!” said Granddaughter Kookaburra and together they continued along the trail.",
        animal_facts: "The Kookaburra’s brown and white feathers help it blend in with the environment, making it more challenging for predators or prey to see them!"
    },
    {
        id: 3,
        name: "brotherwedgetailedeagle",
        image_src: "assets/brotherwedgetailedeagle.png",
        bio_name: "Wedge-tailed Eagle",
        bio_wadawurrung_name: "Bundjil",
        bio_scientific_name: "Aquila audax",
        bio_size_range: "87 - 105 cm",
        bio_weight: "3.2 - 5.3 kg",
        animal_sound_src: "assets/audio/wedgetailedeagle.mp3",
        animal_audio_story_src: "assets/audio/storybrotherwedgetailedeagle.mp3",
        animal_story_para1: "Nanna Kookaburra found Brother Wedge-Tailed Eagle soaring through the trees. “Where are you heading, Nanna Kookaburra?” asked Brother Wedge-Tailed Eagle.",
        animal_story_para2: "“Hello possum!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” called Brother Wedge-Tailed Eagle, who lived in a nest. “It’s somewhere open and free, it is, it’s somewhere open and free.”",
        animal_story_para3: "Brother Wedge Tailed Eagle flapped his big wings and Nanna Kookaburra felt the gentle breeze blow across her beak. Then Nanna Kookaburra continued along the trail.",
        animal_facts: "Unlike most people, whose hair turns white with age, Wedge Tailed Eagles are the opposite! When they are young their feathers are mostly light brown, and as they get older their feathers become more and more black!"
    },
    {
        id: 6,
        name: "sisterwedgetailedeagle",
        image_src: "assets/sisterwedgetailedeagle.png",
        bio_name: "Wedge-tailed Eagle",
        bio_wadawurrung_name: "Bundjil",
        bio_scientific_name: "Aquila audax",
        bio_size_range: "87 - 105 cm",
        bio_weight: "3.2 - 5.3 kg",
        animal_sound_src: "assets/audio/wedgetailedeagle.mp3",
        animal_audio_story_src: "assets/audio/storysisterwedgetailedeagle.mp3",
        animal_story_para1: "Nanna Kookaburra found Sister Wedge-Tailed Eagle perched on a branch. “Where are you heading, Nanna Kookaburra?” asked Sister Wedge-Tailed Eagle.",
        animal_story_para2: "“Hello possum!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” called Sister Wedge-Tailed Eagle, who lived in a nest. “It’s somewhere nice and dry, it is, it’s somewhere nice and dry.”",
        animal_story_para3: "Sister Wedge-Tailed Eagle gave Nanna Kookaburra a grand feather and Nanna Kookaburra continued along the trail.",
        animal_facts: "Wedge Tailed Eagles are very territorial. This means they chase off any other predators that come near their home. Wedge Tailed Eagles have even been known to attack people hang-gliding!"
    },
    {
        id: 7,
        name: "cousinbrushtailpossum",
        image_src: "assets/cousinbrushtailpossum.png",
        bio_name: "Brushtail Possum",
        bio_wadawurrung_name: "Walert",
        bio_scientific_name: "Trichosurus vulpecula",
        bio_size_range: "35 - 55 cm",
        bio_weight: "1.2 - 4.5 kg",
        animal_sound_src: "assets/audio/brushtailpossum.mp3",
        animal_audio_story_src: "assets/audio/storycousinbrushtailpossum.mp3",
        animal_story_para1: "Nanna Kookaburra found Cousin Brushtail Possum in the nook of a tree. “Where are you heading, Nanna Kookaburra?” asked Cousin Brushtail Possum.",
        animal_story_para2: "“Hello possum!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” rumbled Cousin  Brushtail Possum, who was proud she remembered his name, even though she didn’t. “It’s somewhere fun to play, it is, it’s somewhere fun to play.”",
        animal_story_para3: "Cousin Brushtail Possum gave Nanna Kookaburra some stringybark and Nanna Kookaburra continued along the trail.",
        animal_facts: "Brushtailed Possums have prehensile tails. That means they can grasp and hold things with their tail as though it was another hand! They can use their tails to carry grass and twigs for their nests!"
    },
    {
        id: 8,
        name: "cousinringtailpossum",
        image_src: "assets/cousinringtailpossum.png",
        bio_name: "Ringtail Possum",
        bio_wadawurrung_name: "Barnong",
        bio_scientific_name: "Pseudocheirus Peregrinus",
        bio_size_range: "30 cm - 35 cm",
        bio_weight: "0.7 - 1.1 kg",
        animal_sound_src: "assets/audio/ringtailpossum.mp3",
        animal_audio_story_src: "assets/audio/storycousinringtailpossum.mp3",
        animal_story_para1: "Nanna Kookaburra found Cousin Ringtail Possum climbing up a tree trunk. “Where are you heading, Nanna Kookaburra?” asked Cousin Ringtail Possum.",
        animal_story_para2: "“Hello possum!” said Nanna kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” grinned Cousin Ringtail Possum as she swung on a branch by her tail. “It’s somewhere you can be yourself, it is, it’s somewhere you can be yourself.”",
        animal_story_para3: "Cousin Ringtail Possum showed Nanna Kookaburra her funniest face. Nanna Kookaburra laughed and continued along the trail.",
        animal_facts: "A male possum is called a “Jack”, and a female possum is called a “Jill”!"
    },
    {
        id: 9,
        name: "grandadwombat",
        image_src: "assets/grandadwombat.png",
        bio_name: "Wombat",
        bio_wadawurrung_name: "Ngurr-ngurr",
        bio_scientific_name: "Vombatus ursinus",
        bio_size_range: "84 - 115 cm",
        bio_weight: "22 - 39 kg",
        animal_sound_src: "assets/audio/wombat.mp3",
        animal_audio_story_src: "assets/audio/storygrandadwombat.mp3",
        animal_story_para1: "Nanna Kookaburra found Grandad Wombat scratching in the dirt. “Where are you heading, Nanna Kookaburra?” asked Grandad Wombat.",
        animal_story_para2: "“Hello possum!” said Nanna Kookaburra. “I’m heading home love, but I can’t remember where it is.” “Well,” grumped Grandad Wombat who lived in a burrow. “It’s somewhere quiet and cozy, it is, it’s somewhere quiet and cozy.”",
        animal_story_para3: "Grandad Wombat gave Nanna Kookaburra some soft fur and Nanna Kookaburra continued along the trail.",
        animal_facts: "Wombats look big and slow, but they can actually run up to 40km an hour! That’s faster than most people!"
    }
];